🟢 Q1 — Write to Text File

Create a NumPy array:

[10, 20, 30, 40, 50]

Save it to a text file named numbers.txt using np.savetxt().

🟢 Q2 — Read from Text File

Read the numbers.txt file created in Q1 using np.loadtxt() and store the result in a variable named data.

🟢 Q3 — 2D Array + Save

Create the following 2D NumPy array:

[[10, 20],
 [30, 40],
 [50, 60]]

Save it to a text file named sales.txt.

🟡 Q4 — Read + Boolean Indexing

Read sales.txt using np.loadtxt() and store it in a variable named sales.

Then select all values greater than 40.

🟡 Q5 — Read + Replace

Read sales.txt and replace all values greater than 50 with -1.

🔴 Q6 — Mixed Challenge

Create the following NumPy array:

marks = np.array([[45, 78, 90],
                  [33, 88, 67],
                  [95, 42, 76]])
Save it to a text file named marks.txt.
Read the file into a variable named data.
Select all marks greater than 70.
Replace all marks greater than 90 with -1.
Print each row using a for loop.

🟢 Q1 — Write to Text File

Create a NumPy array:

[10, 20, 30, 40, 50]

Save it to a text file named numbers.txt using np.savetxt().

In [1]:
import numpy as np
x = np.array([10, 20, 30, 40, 50])
np.savetxt("numbers.txt",x)

🟢 Q2 — Read from Text File

Read the numbers.txt file created in Q1 using np.loadtxt() and store the result in a variable named data.

In [5]:
result = np.loadtxt("numbers.txt")
result

array([10., 20., 30., 40., 50.])

🟢 Q3 — 2D Array + Save

Create the following 2D NumPy array:

[[10, 20],
 [30, 40],
 [50, 60]]

Save it to a text file named sales.txt.

In [6]:
x = [[10, 20],
 [30, 40],
 [50, 60]]

np.savetxt("sales.txt",x)

🟡 Q4 — Read + Boolean Indexing

Read sales.txt using np.loadtxt() and store it in a variable named sales.

Then select all values greater than 40.

In [7]:
sales = np.loadtxt("sales.txt")
sales

array([[10., 20.],
       [30., 40.],
       [50., 60.]])

🟡 Q5 — Read + Replace

Read sales.txt and replace all values greater than 50 with -1.

In [12]:
sales = np.loadtxt("sales.txt")
sales[sales > 50] = -1
sales

array([[10., 20.],
       [30., 40.],
       [50., -1.]])

🔴 Q6 — Mixed Challenge

Create the following NumPy array:

marks = np.array([[45, 78, 90],
                  [33, 88, 67],
                  [95, 42, 76]])
Save it to a text file named marks.txt.
Read the file into a variable named data.
Select all marks greater than 70.
Replace all marks greater than 90 with -1.
Print each row using a for loop.

In [13]:
marks = np.array([[45, 78, 90],
                  [33, 88, 67],
                  [95, 42, 76]])

In [14]:
np.savetxt("marks.txt",marks)

In [15]:
data = np.loadtxt("marks.txt")
data

array([[45., 78., 90.],
       [33., 88., 67.],
       [95., 42., 76.]])

In [ ]:
data[data > 70]

array([78., 90., 88., 95., 76.])

In [33]:
data = np.loadtxt("marks.txt")
data[data > 90] = -1
data

array([[45., 78., 90.],
       [33., 88., 67.],
       [-1., 42., 76.]])

In [34]:
for row in data:
    print(row)

[45. 78. 90.]
[33. 88. 67.]
[-1. 42. 76.]
