Q1/10 —
A retail company records sales for three stores across three days. Each row represents a store, and each column represents a day.
Calculate the total sales for each store using NumPy.

In [22]:
import numpy as np
sales = np.array([[120, 150, 180],
                  [200, 170, 160],
                  [100, 140, 190]])

sales.sum(axis=1)

array([450, 530, 430])

Q2/10 — Revision
Using the same sales array, calculate the total sales for each day. Each column represents one day.

In [23]:
sales.sum(axis=0)

array([420, 460, 530])

Q3/10 — Broadcasting
A company records the quantity of three products sold over three days. Each row represents a day, and each column represents a product. The product prices are ₹10, ₹20, and ₹15, respectively.
Calculate the revenue for each product on each day, without using loops.

In [24]:
sales = np.array([[10, 20, 15],
                  [12, 18, 16],
                  [9, 21, 17]])

prices = np.array([10, 20, 15])
revenue = sales * prices
revenue


array([[100, 400, 225],
       [120, 360, 240],
       [ 90, 420, 255]])

Q4/10
Using the revenue array from Q3, calculate the total revenue for each day. Each row represents one day.

In [25]:
revenue.sum(axis=1)

array([725, 720, 765])

Q5/10 — Broadcasting + axis
Using the same revenue array, calculate the total revenue for each product across all three day

In [26]:
revenue.sum(axis=0)

array([ 310, 1180,  720])

Q6/10
Using the revenue array from Q3, select and display all individual revenue values greater than ₹300.

In [27]:
revenue[revenue > 300]

array([400, 360, 420])

Q7/10
Using the revenue array, replace all revenue values below ₹250 with 0 and display the modified array.

In [28]:
revenue[revenue < 250] = 0
revenue


array([[  0, 400,   0],
       [  0, 360,   0],
       [  0, 420, 255]])

Q8/10
A company tracks the quantities sold for three products across three months. Each row represents a month, and each column represents a product. Unit prices are ₹20, ₹30, and ₹10, respectively.
Calculate the revenue for each product in every month, then display the complete rows for months whose total revenue is greater than ₹1,000.

In [42]:
sales = np.array([[10, 20, 30],
                  [20, 15, 10],
                  [15, 25, 20]])

prices = np.array([20, 30, 10])

revenue = sales * prices

monthly_total = revenue.sum(axis=1)

filtered_revenue = revenue[monthly_total > 1000]

print(filtered_revenue)

[[200 600 300]
 [300 750 200]]


Q9/10 — Mixed Practice
A company tracks the quantities of three products sold each month. Each row represents a month, and each column represents a product. The unit prices are ₹30, ₹50, and ₹20 for Products A, B, and C, respectively.
Calculate the total revenue for each month, then display only the monthly totals greater than ₹1,000.

In [52]:
sales = np.array([[8, 12, 15],
                  [5, 5, 10],
                  [10, 15, 20]])

prices = np.array([30, 50, 20])
revenue = sales * prices
total_revenue = revenue.sum(axis=1)
total_revenue[total_revenue > 1000]


array([1140, 1450])

Q10/10 — Final Challenge
A company tracks the quantities of three products sold over three months. Each row represents a month, and each column represents a product. Unit prices are ₹40, ₹25, and ₹30 for Products A, B, and C, respectively.
Calculate the total revenue for each product across all three months, then display only the product totals greater than ₹2,000.

In [54]:
sales = np.array([[20, 30, 15],
                  [25, 40, 20],
                  [30, 35, 25]])

prices = np.array([40, 25, 30])

revenue = sales * prices
total_revenue = revenue.sum(axis=0)
total_revenue[total_revenue > 2000]

array([3000, 2625])