🟢 Level 1 — Indexing & Slicing

Q1. Create this 1D array:

[10, 20, 30, 40, 50, 60]

Select:

20, 30, 40
last element

Q2. Create:

a = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

Access:

50
70
last row
first two columns of all rows

Q3. Using the same array, select:

first two rows
last two columns
first two rows and last two columns
🟡 Level 2 — Iteration

Q4. Create a 3 × 3 array containing numbers 1–9.

Print each row using a for loop.

Q5. Using the same array, print every element individually using .flat.

🟡 Level 3 — Stacking

Q6. Create:

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

Perform:

vertical stacking
horizontal stacking

Q7. Create two 2 × 3 arrays and use vstack() to combine them.

Then use hstack() to combine them.

🟠 Level 4 — Splitting

Q8. Create a 2 × 6 array containing numbers 1–12.

Split it into 3 equal parts horizontally using hsplit().

Q9. Create a 4 × 3 array containing numbers 1–12.

Split it into 2 equal parts vertically using vsplit().

🟠 Level 5 — Boolean Indexing

Q10. Create:

a = np.array([10, 25, 5, 40, 15, 30])

Select all values greater than 20 using Boolean indexing.

Q11. Using the same array, select all values less than 15.

Q12. Create:

a = np.arange(12).reshape(3, 4)

Select all values greater than 5 using Boolean indexing.

🔴 Level 6 — Data Analytics Style

Q13. Monthly sales:

sales = np.array([12000, 18000, 9000, 25000, 15000, 30000])

Select months where sales are greater than 15,000.

Q14. Employee salaries:

salary = np.array([25000, 40000, 30000, 55000, 35000])

Select salaries greater than 30,000.

Then replace those selected salaries with -1.

⭐ Q15 — Mixed Challenge
sales = np.array([[100, 150, 200],
                  [250, 120, 300],
                  [180, 220, 90]])
Select the last two columns.
Select all sales values greater than 200.
Replace values greater than 200 with -1.
Print each row using a for loop.

🟢 Level 1 — Indexing & Slicing

Q1. Create this 1D array:

[10, 20, 30, 40, 50, 60]

Select:

20, 30, 40
last element

In [53]:
import numpy as np
a = np.array([10, 20, 30, 40, 50, 60])
a[1:4]

array([20, 30, 40])

Q2. Create:

a = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

Access:

50
70
last row
first two columns of all rows

In [3]:
a = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

In [4]:
a[1,1]

np.int64(50)

In [5]:
a[2,0]

np.int64(70)

In [6]:
a[-1]

array([70, 80, 90])

In [9]:
a[:,0:2]

array([[10, 20],
       [40, 50],
       [70, 80]])

Q3. Using the same array, select:

first two rows
last two columns
first two rows and last two columns

In [12]:
a[:2]

array([[10, 20, 30],
       [40, 50, 60]])

In [15]:
a[:,-2:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [16]:
a[:2, -2:]

array([[20, 30],
       [50, 60]])

🟡 Level 2 — Iteration
Q4. Create a 3 × 3 array containing numbers 1–9.

Print each row using a for loop.


In [22]:
a = np.array([[6,7,8],[1,2,3],[9,3,2]])
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


Q5. Using the same array, print every element individually using .flat.

In [23]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


🟡 Level 3 — Stacking

Q6. Create:

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

Perform:

vertical stacking
horizontal stacking

In [24]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

In [25]:
np.stack((a,b))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [26]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Q7. Create two 2 × 3 arrays and use vstack() to combine them.

Then use hstack() to combine them.

In [ ]:
a= np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [34]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [35]:
np.hstack((a,b))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

🟠 Level 4 — Splitting

Q8. Create a 2 × 6 array containing numbers 1–12.

Split it into 3 equal parts horizontally using hsplit().

In [37]:
a = np.arange(12).reshape(2,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [40]:
np.hsplit(a,3)

[array([[0, 1],
        [6, 7]]),
 array([[2, 3],
        [8, 9]]),
 array([[ 4,  5],
        [10, 11]])]

Q9. Create a 4 × 3 array containing numbers 1–12.

Split it into 2 equal parts vertically using vsplit().

In [42]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
np.vsplit(a,2)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]])]

🟠 Level 5 — Boolean Indexing

Q10. Create:

a = np.array([10, 25, 5, 40, 15, 30])

Select all values greater than 20 using Boolean indexing.

In [47]:
a = np.array([10, 25, 5, 40, 15, 30])
b = 20
a > b


array([False,  True, False,  True, False,  True])

Q11. Using the same array, select all values less than 15.

In [ ]:
a < 15

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

Q12. Create:

a = np.arange(12).reshape(3, 4)

Select all values greater than 5 using Boolean indexing.

In [50]:
a = np.arange(12).reshape(3, 4)
b = a > 5
b

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

🔴 Level 6 — Data Analytics Style

Q13. Monthly sales:

sales = np.array([12000, 18000, 9000, 25000, 15000, 30000])

Select months where sales are greater than 15,000.

In [58]:
sales = np.array([12000, 18000, 9000, 25000, 15000, 30000])
sales[sales>15000]

array([18000, 25000, 30000])

Q14. Employee salaries:

salary = np.array([25000, 40000, 30000, 55000, 35000])

Select salaries greater than 30,000.

Then replace those selected salaries with -1.

In [79]:
salary = np.array([25000, 40000, 30000, 55000, 35000])
salary[salary > 30000]

array([40000, 55000, 35000])

In [81]:
salary[salary > 30000] = -1
print(salary)

[25000    -1 30000    -1    -1]


⭐ Q15 — Mixed Challenge
sales = np.array([[100, 150, 200],
                  [250, 120, 300],
                  [180, 220, 90]])
Select the last two columns.
Select all sales values greater than 200.
Replace values greater than 200 with -1.
Print each row using a for loop.

In [108]:
sales = np.array([[100, 150, 200],
                  [250, 120, 300],
                  [180, 220, 90]])
sales

array([[100, 150, 200],
       [250, 120, 300],
       [180, 220,  90]])

In [109]:
sales[:,-2:]

array([[150, 200],
       [120, 300],
       [220,  90]])

In [110]:
sales[sales > 200]

array([250, 300, 220])

In [111]:
sales[sales > 200] = -1
print(sales)

[[100 150 200]
 [ -1 120  -1]
 [180  -1  90]]


In [112]:
for row in sales:
    print(row)

[100 150 200]
[ -1 120  -1]
[180  -1  90]
