🟢 Q1 — Row Iteration

Create this NumPy array:

a = np.arange(12).reshape(3,4)

Use a for loop to print each row.

🟢 Q2 — Element Iteration

Using the same array, print each individual element using a nested for loop.

🟢 Q3 — flatten()

Create a 3×4 NumPy array and use flatten() to print all elements one by one.

🟢 Q4 — nditer() Basic

Create a 3×4 NumPy array and use np.nditer() to print each element one by one.

🟢 Q5 — C Order

Create this array:

[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]

Use np.nditer() with order='C' to print all elements.

🟢 Q6 — F Order

Use the same array from Q5 and iterate through its elements using order='F'.

🟡 Q7 — C vs F Order

Create a 3×4 array and:

Iterate through it using C order.
Iterate through it using F order.

Observe the difference in the output.

🟡 Q8 — external_loop

Create a 3×4 array and use np.nditer() with:

flags=['external_loop']

Observe how the elements are returned.

🟡 Q9 — readwrite

Create:

a = np.arange(1,10).reshape(3,3)

Use np.nditer() with op_flags=['readwrite'] to store the square of each element back into the original array.

🟡 Q10 — Replace Using readwrite

Create:

a = np.arange(1,13).reshape(3,4)

Using nditer() with readwrite, replace all even numbers with -1.

🟡 Q11 — Iterate Through Two Arrays

Create:

a = np.array([1,2,3])
b = np.array([10,20,30])

Use np.nditer([a,b]) to print the corresponding elements of both arrays.

Expected format:

1 10
2 20
3 30
🔴 Q12 — Broadcasting with nditer()

Create:

a = np.arange(12).reshape(3,4)
b = np.array([10,20,30,40])

Use np.nditer([a,b]) to print the corresponding values from both arrays.

🔴 Q13 — Two Arrays Calculation

Using the arrays from Q12, use nditer() to add the corresponding value from b to each element of a and print the result.

🔴 Q14 — Interview Style

Create a 3×4 array.

Using nditer():

Calculate the sum of all elements using C order.
Calculate the sum of all elements using F order.
Check whether both sums are the same.
🔴 Q15 — Mixed Challenge

Create:

a = np.arange(1,13).reshape(3,4)

Using only the concepts covered in Lecture 6:

Print each row.
Use flatten() to print all elements.
Iterate using nditer() with C order.
Iterate using nditer() with F order.
Use readwrite to multiply every element by 2.
Print the final array.

🟢 Q1 — Row Iteration

Create this NumPy array:

a = np.arange(12).reshape(3,4)

Use a for loop to print each row.

In [2]:
import numpy as np
a = np.arange(12).reshape(3,4)
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


🟢 Q2 — Element Iteration

Using the same array, print each individual element using a nested for loop.

In [3]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


🟢 Q3 — flatten()

Create a 3×4 NumPy array and use flatten() to print all elements one by one.

In [7]:
b  = np.arange(12).reshape(3,4)
for cell in b.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


🟢 Q4 — nditer() Basic

Create a 3×4 NumPy array and use np.nditer() to print each element one by one.

In [13]:
a = np.arange(12).reshape(3,4)
for x in np.nditer(a,order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


🟢 Q5 — C Order

Create this array:

[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]

Use np.nditer() with order='C' to print all elements.

In [16]:
arr = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

for i in np.nditer(arr,order='C'):
    print(i)

1
2
3
4
5
6
7
8
9


🟢 Q6 — F Order

Use the same array from Q5 and iterate through its elements using order='F'.

In [17]:
for i in np.nditer(arr,order='F'):
    print(i)

1
4
7
2
5
8
3
6
9


🟡 Q7 — C vs F Order

Create a 3×4 array and:

Iterate through it using C order.
Iterate through it using F order.

Observe the difference in the output.

In [18]:
arr = np.arange(12).reshape(3,4)
for i in np.nditer(arr,order='C'):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [19]:
for i in np.nditer(arr,order='F'):
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11


🟡 Q8 — external_loop

Create a 3×4 array and use np.nditer() with:

flags=['external_loop']

Observe how the elements are returned.

In [26]:
arr = np.arange(12).reshape(3,4)
for i in np.nditer(arr,order='C', flags=['external_loop']):
    print(i)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


🟡 Q9 — readwrite

Create:

a = np.arange(1,10).reshape(3,3)

Use np.nditer() with op_flags=['readwrite'] to store the square of each element back into the original array.

In [28]:
a = np.arange(1,10).reshape(3,3)
for i in np.nditer(a,op_flags=['readwrite']):
    i[...]=i*i

a

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

🟡 Q10 — Replace Using readwrite

Create:

a = np.arange(1,13).reshape(3,4)

Using nditer() with readwrite, replace all even numbers with -1.

In [38]:
a = np.arange(1,13).reshape(3,4)
for i in np.nditer(a,op_flags=['readwrite']):
    if i % 2 == 0:
        i[...]=-1
a

array([[ 1, -1,  3, -1],
       [ 5, -1,  7, -1],
       [ 9, -1, 11, -1]])

🟡 Q11 — Iterate Through Two Arrays

Create:

a = np.array([1,2,3])
b = np.array([10,20,30])

Use np.nditer([a,b]) to print the corresponding elements of both arrays.

Expected format:

1 10
2 20
3 30

In [ ]:
a = np.array([1,2,3])
b = np.array([10,20,30])
for x,y in np.nditer([a,b]):
    print(x,y)

1 10
2 20
3 30


🔴 Q12 — Broadcasting with nditer()

Create:

a = np.arange(12).reshape(3,4)
b = np.array([10,20,30,40])

Use np.nditer([a,b]) to print the corresponding values from both arrays.

In [43]:
a = np.arange(12).reshape(3,4)
b = np.array([10,20,30,40])
for x,y in np.nditer([a,b]):
    print(x,y)


0 10
1 20
2 30
3 40
4 10
5 20
6 30
7 40
8 10
9 20
10 30
11 40


🔴 Q13 — Two Arrays Calculation

Using the arrays from Q12, use nditer() to add the corresponding value from b to each element of a and print the result.

In [53]:
a = np.arange(12).reshape(3,4)
b = np.array([10,20,30,40])
for x,y in np.nditer([a,b]):
    print(x + y)

10
21
32
43
14
25
36
47
18
29
40
51


🔴 Q14 — Interview Style

Create a 3×4 array.

Using nditer():

Calculate the sum of all elements using C order.
Calculate the sum of all elements using F order.
Check whether both sums are the same.

In [59]:
arr = np.arange(12).reshape(3,4)
total = 0
for i in np.nditer(arr,order='C'):
    total = total + i

print(total)

66


In [60]:
total = 0
for i in np.nditer(arr,order='F'):
    total = total + i

print(total)

66


🔴 Q15 — Mixed Challenge

Create:

a = np.arange(1,13).reshape(3,4)

Using only the concepts covered in Lecture 6:

Print each row.
Use flatten() to print all elements.
Iterate using nditer() with C order.
Iterate using nditer() with F order.
Use readwrite to multiply every element by 2.
Print the final array.

In [62]:
a = np.arange(1,13).reshape(3,4)

In [64]:
for i in a.flatten():
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [66]:
for i in np.nditer(a,order='C'):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [67]:
for i in np.nditer(a,order='F'):
    print(i)

1
5
9
2
6
10
3
7
11
4
8
12


In [79]:
a = np.arange(1,13).reshape(3,4)
for i in np.nditer(a,order='C',op_flags=['readwrite']):
    i[...] = i * 2
print(a)


[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
