Q1 — Indexing & Slicing
Given:
a = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
Write NumPy code to print:
1. The element 50
2. The last row
3. The first 2 rows and last 2 columns
Use indexing/slicing only.

In [2]:
import numpy as np
a = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
print(a[1,1])
print(a[-1,:])
print(a[0:2,-2:])

50
[70 80 90]
[[20 30]
 [50 60]]


Q2 — Boolean Indexing
a = np.arange(1, 13).reshape(3, 4)
Write code to:
1. Select all even numbers
2. Replace all even numbers with -1

In [ ]:
a = np.arange(1, 13).reshape(3, 4)
a[a % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [19]:
a[a % 2 == 0] = -1
a

array([[ 1, -1,  3, -1],
       [ 5, -1,  7, -1],
       [ 9, -1, 11, -1]])

Q3 — Lecture 3 Retention
Given:
a = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
Using slicing only, print:
The first 2 columns of all rows.

In [21]:
a = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
a[:,0:2]

array([[10, 20],
       [40, 50],
       [70, 80]])

Q4 — Lecture 3 Retention
Given:
a = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
Using slicing, print:
The last 2 rows and the first 2 columns.

In [25]:
a = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
a[-2:,0:2]

array([[40, 50],
       [70, 80]])

Q5/10
Given:
a = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
Use .flat to print every element one by one.

In [27]:
a = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
for i in a.flat:
    print(i)

10
20
30
40
50
60
70
80
90


Q6
Given:
a = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
Save this array into a text file named sales.txt using NumPy.

In [ ]:
a = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
np.savetxt("Sales.txt",a)

Q7. Read the data from Sales.txt into a NumPy array named b.

In [ ]:
b = np.loadtxt("Sales.txt")

Q8. Read the data from Sales.txt into a NumPy array named b, then select and print all values greater than 40.

In [36]:
b = np.loadtxt('Sales.txt')
b[ b > 40]

array([50., 60., 70., 80., 90.])

Q9. Read Sales.txt into b, then replace all values greater than 50 with -1.

In [38]:
b = np.loadtxt('Sales.txt')
b[b > 50] = -1
b

array([[10., 20., 30.],
       [40., 50., -1.],
       [-1., -1., -1.]])

Q10
Given:
marks = np.array([[45, 78, 90],[33, 88, 67],[95, 42, 76]])
Save marks to marks.txt, then load it into a new NumPy array named data.

In [42]:
marks = np.array([[45, 78, 90],[33, 88, 67],[95, 42, 76]])
np.savetxt("marks.txt",marks)
data = np.loadtxt("marks.txt")

Q11. Create the following NumPy array and save it to a text file named numbers.txt:
np.array([10, 20, 30, 40, 50])

In [3]:
a = np.array([10, 20, 30, 40, 50])
np.savetxt('numbers.txt',a)

Q12. Read numbers.txt into a NumPy array named data and print data.

In [5]:
b = np.loadtxt("numbers.txt")
b

array([10., 20., 30., 40., 50.])

Q13. Read marks.txt into a NumPy array named data, then select and print all marks greater than 70.

In [7]:
data = np.loadtxt("marks.txt")
data[data > 70]

array([78., 90., 88., 95., 76.])

Q14. Read marks.txt into a NumPy array named data, then replace all marks greater than 90 with -1 and display the modified array.

In [8]:
data = np.loadtxt("marks.txt")
data[data > 90] = -1
print(data)

[[45. 78. 90.]
 [33. 88. 67.]
 [-1. 42. 76.]]


Q15/15
Given:
marks = np.array([[45, 78, 90],[93, 88, 67],[95, 42, 76]])
Save marks to marks2.txt, load it into data, then replace all values greater than 80 with -1 and display the final array.

In [16]:
marks = np.array([[45, 78, 90],[33, 88, 67],[95, 42, 76]])
np.savetxt("marks2.txt",marks)
data = np.loadtxt("marks2.txt")
data[data > 80] = -1
print(data)

[[45. 78. -1.]
 [33. -1. 67.]
 [-1. 42. 76.]]
