Q1 — Array Creation & Properties 🟢

Create this NumPy array:

[10, 20, 30, 40, 50, 60]

Then print:

Number of dimensions
Shape
Number of elements
Data type
Item size

In [7]:
import numpy as np
a = np.array([10, 20, 30, 40, 50, 60])
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

1
(6,)
6
int64
8


Q2 — Indexing + Slicing

Create this array:

[10, 20, 30, 40, 50, 60, 70, 80]

Find:

First element
Last element
Elements from index 2 to 5
Last 3 elements
Elements at index 1, 3, and 5

In [17]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(arr[0])
print(arr[-1])
print(arr[2:6])
print(arr[-3:])
print(arr[[1, 3, 5]])

10
80
[30 40 50 60]
[60 70 80]
[20 40 60]


Q3 — 2D Indexing + Slicing

Create:

[[10, 20, 30],
 [40, 50, 60],
 [70, 80, 90]]

Find:

50
30
Last row
First column
First 2 rows and last 2 columns

In [34]:
a = np.array([[10, 20, 30],
 [40, 50, 60],
 [70, 80, 90]])

print(a[1,[1]])
print(a[0,[2]])
print(a[-1])
print(a[:,0])
print(a[0:2,1:3])

[50]
[30]
[70 80 90]
[10 40 70]
[[20 30]
 [50 60]]


Q4 — Iteration

Given:

a = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

Without using flatten() or nditer(), print each individual element one by one.

In [39]:
a = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])
for row in a:
    for cell in row:
        print(cell)

10
20
30
40
50
60
70
80
90


Q5 — flatten() + Iteration

Given:

a = np.array([[1, 2, 3],
              [4, 5, 6]])

Use flatten() to convert it into a 1D array, then print each element one by one.

In [43]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

for i in a.flatten():
    print(i)

1
2
3
4
5
6


Q6 — np.nditer() Basic

Given:

a = np.array([[10, 20, 30],
              [40, 50, 60]])

Use np.nditer() to print each element one by one.

In [45]:
a = np.array([[10, 20, 30],
              [40, 50, 60]])
for row in np.nditer(a):
    print(row)

10
20
30
40
50
60


Q7 — nditer() C Order vs F Order

Given the array:

a = np.array([[1, 2, 3],
              [4, 5, 6]])

Using np.nditer():

Print all elements in C order.
Print all elements in F order.

Write the code for both separately.

In [46]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

for i in np.nditer(a,order='C'):
    print(i)

1
2
3
4
5
6


In [47]:
for i in np.nditer(a,order='F'):
    print(i)

1
4
2
5
3
6


Q8 — external_loop

Given:

a = np.arange(12).reshape(3, 4)

Use np.nditer() with external_loop and print the output.

In [51]:
a = np.arange(12).reshape(3,4)
for x in np.nditer(a,flags=['external_loop']):
    print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


Q9 — readwrite

Given:

a = np.arange(1, 7).reshape(2, 3)

Use np.nditer() with op_flags=['readwrite'] and multiply every element by 2

In [54]:
a = np.arange(1, 7).reshape(2, 3)
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=x*2
    print(a)

[[2 2 3]
 [4 5 6]]
[[2 4 3]
 [4 5 6]]
[[2 4 6]
 [4 5 6]]
[[2 4 6]
 [8 5 6]]
[[ 2  4  6]
 [ 8 10  6]]
[[ 2  4  6]
 [ 8 10 12]]


Q10 — Final for today
a = np.arange(1, 7).reshape(2, 3)
b = np.array([10, 20, 30])

Using np.nditer(), add corresponding values of a and b and print each result.

Expected output:

11, 22, 33, 14, 25, 36

In [57]:
a = np.arange(1, 7).reshape(2, 3)
b = np.array([10, 20, 30])
for x,y in np.nditer([a,b]):
    print(x+y)

11
22
33
14
25
36
