Lecture 2 — Q1
Create this array:
[[10, 20, 30],
 [40, 50, 60]]

Then print:
1. Number of dimensions
2. Shape
3. Number of elements
4. Data type
5. Size of each element in bytes

In [17]:
import numpy as np
a = np.array([[10, 20, 30],
 [40, 50, 60]])

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

2
(2, 3)
6
int64
8


Lecture 2 — Q2
Given:
a = np.array([[10, 20, 30],              [40, 50, 60]])


Use reshape() to convert this array into a 3 × 2 array.
Print the reshaped array.
No hint — write it from memory.

In [18]:
a = np.array([[10, 20, 30],[40, 50, 60]])
a.reshape(3,2)

array([[10, 20],
       [30, 40],
       [50, 60]])

Q3 — reshape() + 1D
Given:
a = np.array([[1, 2],[3, 4],[5, 6]])
Use reshape() to convert it into a 1D array containing all 6 elements.
Print the result.

In [22]:
a = np.array([[1, 2],[3, 4],[5, 6]])
a.reshape(6)

array([1, 2, 3, 4, 5, 6])

Q4 — ravel()
Given:
a = np.array([[1, 2],[3, 4],[5, 6]])
Use ravel() to convert the 2D array into a 1D array.
Print the result.

In [26]:
a = np.array([[1, 2],[3, 4],[5, 6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

Q5 — Aggregate Functions
Given:
a = np.array([[10, 20, 30],[40, 50, 60]])


Print:
1. Minimum value
2. Maximum value
3. Sum of all elements

In [29]:
a = np.array([[10, 20, 30],[40, 50, 60]])
print(a.min())
print(a.max())
print(a.sum())

10
60
210


Q6 — Axis
Given:
a = np.array([[10, 20, 30],[40, 50, 60]])

Find the sum of each column using axis.
No loop.

In [31]:
a = np.array([[10, 20, 30],[40, 50, 60]])
a.sum(axis=0)

array([50, 70, 90])

Q7 — Axis
Using the same array:
a = np.array([[10, 20, 30],[40, 50, 60]])

Find the sum of each row using axis.
No loop.

In [32]:
a = np.array([[10, 20, 30],[40, 50, 60]])
a.sum(axis=1)

array([ 60, 150])

Q8 — sqrt()
Given:
a = np.array([1, 4, 9, 16, 25])

Use NumPy to calculate the square root of every element and print the result.
Write it without a loop.

In [37]:
a = np.array([1, 4, 9, 16, 25])
np.sqrt(a)

array([1., 2., 3., 4., 5.])

Q9 — Standard Deviation
Given:
a = np.array([10, 20, 30, 40, 50])

Use NumPy to calculate the standard deviation of the array.
No loop.

In [38]:
a = np.array([10, 20, 30, 40, 50])
np.std(a)

np.float64(14.142135623730951)

Q10 — Array Arithmetic
Given:
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])

Perform and print:
1. Element-wise addition
2. Element-wise division
3. Element-wise multiplication
Use NumPy array operations only. No loop.

In [41]:
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])
print(a+b)
print(a/b)
print(a*b)

[[ 6  8]
 [10 12]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[ 5 12]
 [21 32]]


Q11 — Lecture 2: Matrix Multiplication
Using:
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])

Perform matrix multiplication of a and b.

In [43]:
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])
a.dot(b)

array([[19, 22],
       [43, 50]])

Q12 — linspace()
Create 10 evenly spaced numbers between 1 and 5, including both 1 and 5.
Use np.linspace() and print the result.
Write the code from memory.

In [44]:
a = np.linspace(1,5,10)
a

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

Q13 — zeros() and ones()
Create:
1. A 3 × 4 array of zeros
2. A 2 × 5 array of ones
Use NumPy functions and print both arrays.

In [48]:
a = np.zeros([3,4])
b = np.ones([2,5])
a,b

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

Q14 — dtype + itemsize
Create this array:
[10, 20, 30, 40]
with float32 data type.
Then print:
1. dtype
2. itemsize
Write the code yourself.

In [53]:
a = np.array([10, 20, 30, 40], 'float32')
print(a.dtype)
print(a.itemsize)

float32
4


Q15 — Final Lecture 2 Challenge
Create this array:
[[10, 20, 30],
 [40, 50, 60],
 [70, 80, 90]]

Then print:
1. Mean of all elements
2. Standard deviation
3. Minimum value
4. Maximum value

In [56]:
a = np.array([[10, 20, 30],
 [40, 50, 60],
 [70, 80, 90]])

print(a.mean())
print(np.std(a))
print(a.min())
print(a.max())

50.0
25.81988897471611
10
90
