Q1/15 — 1D Indexing
Given:
import numpy as np
np.array([10, 20, 30, 40, 50, 60])

Print:
1. The first element
2. The last element
3. The element at index 3
Write the code yourself.

In [4]:
import numpy as np
a = np.array([10, 20, 30, 40, 50, 60])
print(a[0])
print(a[-1])
print(a[3])

10
60
40


Q2 — 1D Slicing
Given the same array:
a = np.array([10, 20, 30, 40, 50, 60])
Print:
1. Elements from index 1 to 4
2. The first 3 elements
3. The last 2 elements
Write the code without a hint.

In [9]:
a = np.array([10, 20, 30, 40, 50, 60])
print(a[1:5])
print(a[:3])
print(a[-2:])

[20 30 40 50]
[10 20 30]
[50 60]


Q3 — 2D Indexing
Given:
a = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
Print:
1. 50
2. 30
3. The last row
Write the code yourself.

In [14]:
a = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
print(a[1,1])
print(a[0,2])
print(a[-1])

50
30
[70 80 90]


Q4 — 2D Slicing
Given:
a = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
Print:
1. The first 2 rows
2. The last 2 columns
3. The first 2 rows and last 2 columns
Write all three using slicing.

In [28]:
a = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
print(a[:2])
print(a[:,-2:])
print(a[:2,-2:])

[[10 20 30]
 [40 50 60]]
[[20 30]
 [50 60]
 [80 90]]
[[20 30]
 [50 60]]


Q5 — Row Iteration
Given:
a = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
Use a for loop to print each row separately.
Write it from memory.

In [30]:
a = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
for row in a:
    print(row)


[10 20 30]
[40 50 60]
[70 80 90]


Q6 — Element Iteration
Using the same 2D array, print each individual element one by one.
Use the Lecture 3 method you learned with .flat.
No nested loop this time

In [35]:
for cell in a.flat:
    print(cell)

10
20
30
40
50
60
70
80
90


Q7 — vstack()
Given:
a = np.array([[1, 2],[3, 4]])b = np.array([[5, 6],[7, 8]])
Use np.vstack() to stack b below a.
Print the resulting array.

In [40]:
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Q8 — hstack()
Given:
a = np.array([[1, 2],[3, 4]])b = np.array([[5, 6],[7, 8]])
Use np.hstack() to stack b to the right of a.
Print the resulting array.

In [42]:
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Q9 — hsplit()
Given:
a = np.arange(12).reshape(2, 6)
Use np.hsplit() to split the array into 3 equal parts.
Print the result.

In [44]:
a = np.arange(12).reshape(2, 6)
np.hsplit(a,3)

[array([[0, 1],
        [6, 7]]),
 array([[2, 3],
        [8, 9]]),
 array([[ 4,  5],
        [10, 11]])]

Q10 — vsplit()
Given:
a = np.arange(12).reshape(6, 2)
Use np.vsplit() to split the array into 3 equal parts.
Print the result.
Write it from memory.

In [45]:
a = np.arange(12).reshape(6, 2)
np.vsplit(a,3)

[array([[0, 1],
        [2, 3]]),
 array([[4, 5],
        [6, 7]]),
 array([[ 8,  9],
        [10, 11]])]

Q11 — Boolean Indexing
Given:
a = np.array([10, 25, 40, 55, 70, 85])
Create a Boolean condition to select only the elements greater than 50, then print those elements.
Use the Lecture 3 Boolean indexing method.

In [48]:
a = np.array([10, 25, 40, 55, 70, 85])
a[a > 50 ]

array([55, 70, 85])

Q12 — Boolean Indexing + Replacement
Given:
a = np.array([10, 25, 40, 55, 70, 85])
Replace all values greater than 50 with -1.
Then print the modified array.
Use Boolean indexing.

In [50]:
a = np.array([10, 25, 40, 55, 70, 85])
a[a > 50] = -1
a

array([10, 25, 40, -1, -1, -1])

Q13 — Boolean Indexing: Even Values
Given:
a = np.array([10, 15, 20, 25, 30, 35, 40])
Select and print only the even numbers using Boolean indexing.
No loop.

In [57]:
a = np.array([10, 15, 20, 25, 30, 35, 40])
a[a % 2 == 0]

array([10, 20, 30, 40])

Q14 — Boolean Indexing + Replacement
Given:
a = np.array([10, 15, 20, 25, 30, 35, 40])
Replace all even numbers with -1 and print the modified array.

In [59]:
a = np.array([10, 15, 20, 25, 30, 35, 40])
a[a % 2 == 0] = -1
print(a)

[-1 15 -1 25 -1 35 -1]


Q15/15 — Boolean Indexing Final Challenge
Given:
a = np.array([10, 25, 40, 55, 70, 85, 100])

Replace all values greater than 50 with 0, then print the modified array.
Do it without a loop.

In [61]:
a = np.array([10, 25, 40, 55, 70, 85, 100])
a[a > 50] = 0
print(a)

[10 25 40  0  0  0  0]
