Q1/10
Given the following sales data:
sales = np.array([[101, 250, 3],[102, 600, 5],[103, 450, 2],[104, 800, 6]])
Save the array to sales.txt, load it into data, and print the rows where the second column value is greater than 500.

In [ ]:
import numpy as np 
sales = np.array([[101, 250, 3],[102, 600, 5],[103, 450, 2],[104, 800, 6]])
np.savetxt("sales.txt",sales)
data = np.loadtxt("sales.txt")
print(data[data[:, 1] > 500])


[[102. 600.   5.]
 [104. 800.   6.]]


Q2/10
Given the order data below, calculate the revenue for each order by multiplying the unit price by the quantity, then display only the orders whose revenue is greater than ₹1,000.

In [19]:
orders = np.array([[101, 250, 3],
                   [102, 600, 2],
                   [103, 450, 1],
                   [104, 200, 6]])

revenue = orders[: ,1] * orders[:,2]
orders[revenue > 1000]

array([[102, 600,   2],
       [104, 200,   6]])

Q3/10
Given a 2D NumPy array of monthly sales, replace all values below 500 with 0, then display the modified array.

In [31]:
sales = np.array([[650, 420, 800],
                  [300, 550, 470],
                  [900, 250, 700]])
sales[sales < 500] =0
sales

array([[650,   0, 800],
       [  0, 550,   0],
       [900,   0, 700]])

Q4/10
A company tracks monthly sales across three stores. Calculate the total sales for each month using NumPy

In [33]:
sales = np.array([[120, 150, 180],
                  [100, 200, 160],
                  [130, 170, 190]])
sales.sum(axis=1)

array([450, 460, 490])

Q5/10
Using the same sales array, calculate the total sales across all months for each store.

In [35]:
sales.sum(axis=0)

array([350, 520, 530])

Q6/10 — Broadcasting
NumPy broadcasting lets you perform operations between compatible array shapes without using loops.
A store tracks weekly sales of three products:
Calculate the revenue for each product in every week using NumPy, without using loops.

In [42]:
sales = np.array([[100, 200, 150],
                  [120, 180, 160],
                  [90, 210, 170],
                  [140, 190, 180]])

prices = np.array([10, 20, 15])
revenue = prices * sales
revenue

array([[1000, 4000, 2250],
       [1200, 3600, 2400],
       [ 900, 4200, 2550],
       [1400, 3800, 2700]])

Q7/10
The following array stores monthly sales quantities for two products. Each row represents a month, and the two columns represent Product A and Product B. Their unit prices are ₹50 and ₹80, respectively.
Calculate the revenue for each product in every month using NumPy.

In [44]:
sales = np.array([[10, 20],
                  [15, 12],
                  [8,  25]])

prices = np.array([50, 80])
revenue = sales * prices
revenue

array([[ 500, 1600],
       [ 750,  960],
       [ 400, 2000]])

Q8.Using the revenue array from Q7, select and display all revenue values greater than ₹1,000.

In [48]:
revenue[revenue > 1000]

array([1600, 2000])

Q9/10
Using the revenue array from Q7, calculate the total revenue for each month. Each row represents one month.

In [51]:
revenue.sum(axis=1)

array([2100, 1710, 2400])

Q10/10
A company tracks the quantities sold for three products across four weeks. Each row represents a week, and each column represents a product. Unit prices are ₹10, ₹20, and ₹15 for Products A, B, and C, respectively.
Calculate the revenue for each product in every week, then calculate the total revenue across all four weeks for each product.

In [59]:
sales = np.array([[100, 200, 150],
                  [120, 180, 160],
                  [90, 210, 170],
                  [140, 190, 180]])

prices = np.array([10, 20, 15])

revenue = sales * prices
print(revenue)

total_revenue = revenue.sum(axis=0)
print(total_revenue)

[[1000 4000 2250]
 [1200 3600 2400]
 [ 900 4200 2550]
 [1400 3800 2700]]
[ 4500 15600  9900]
