## NumPy Lecture 1 — Practice Questions

### **Q1. Import NumPy**

Import NumPy using the standard alias `np`.

### **Q2. Create a NumPy Array**

Create a NumPy array using the list `[10, 20, 30, 40, 50]` and print it.

### **Q3. Add Two Arrays**

Create two arrays:

* `[1, 2, 3, 4, 5]`
* `[10, 20, 30, 40, 50]`

Add both arrays element-wise and display the output.

### **Q4. Array Subtraction**

Using the two arrays from **Q3**, subtract the first array from the second array.

### **Q5. Array Multiplication**

Multiply the two arrays from **Q3** element-wise.

### **Q6. Array Division**

Divide the second array by the first array element-wise.

### **Q7. Python List vs NumPy Memory**

Create a Python list and a NumPy array, both containing $1,000$ elements. Compare their memory consumption.

> **Hint:** Use `sys.getsizeof()` for the Python list and `.nbytes` for the NumPy array.

### **Q8. Python List vs NumPy Speed**

Create two Python lists of $1,000,000$ elements each and measure the execution time for their element-wise addition. Then perform the exact same operation using two NumPy arrays and compare the execution times.

> **Hint:** Use `time.perf_counter()` or `%timeit` in Jupyter Notebook.

### **Q9. Observe Practical Differences (Broadcasting)**

Take the following two structures:

* **Python list:** `[1, 2, 3]`
* **NumPy array:** `np.array([1, 2, 3])`

Multiply both by `2` and observe the difference in outputs.

### **Q10. Mini Task ⭐**

Given two lists:

* `prices = [100, 200, 300, 400, 500]`
* `quantity = [2, 3, 1, 4, 2]`

Use NumPy to calculate the total amount for each item ($\text{price} \times \text{quantity}$).

---

### **Q1. Import NumPy**

Import NumPy using the standard alias `np`.

In [14]:
import numpy as np
import time
import sys

### **Q2. Create a NumPy Array**

Create a NumPy array using the list `[10, 20, 30, 40, 50]` and print it.

In [15]:
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

### **Q3. Add Two Arrays**

Create two arrays:

* `[1, 2, 3, 4, 5]`
* `[10, 20, 30, 40, 50]`

Add both arrays element-wise and display the output.

In [16]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
a+b

array([11, 22, 33, 44, 55])

### **Q4. Array Subtraction**

Using the two arrays from **Q3**, subtract the first array from the second array.

In [17]:
a-b

array([ -9, -18, -27, -36, -45])

### **Q5. Array Multiplication**

Multiply the two arrays from **Q3** element-wise.

In [18]:
a*b

array([ 10,  40,  90, 160, 250])

### **Q6. Array Division**

Divide the second array by the first array element-wise.

In [19]:
a/b

array([0.1, 0.1, 0.1, 0.1, 0.1])

### **Q7. Python List vs NumPy Memory**

Create a Python list and a NumPy array, both containing $1,000$ elements. Compare their memory consumption.

> **Hint:** Use `sys.getsizeof()` for the Python list and `.nbytes` for the NumPy array.

In [20]:
l = range(1000)
sys.getsizeof(5)*len(l)

28000

In [21]:
a = np.arange(1000)
a.nbytes

8000

### **Q8. Python List vs NumPy Speed**

Create two Python lists of $1,000,000$ elements each and measure the execution time for their element-wise addition. Then perform the exact same operation using two NumPy arrays and compare the execution times.

> **Hint:** Use `time.perf_counter()` or `%timeit` in Jupyter Notebook.

In [22]:
size = 1000000

l1 = list(range(size))
l2 = list(range(size))
start = time.perf_counter()
result = [x + y for x, y in zip(l1, l2)]
python_time = time.perf_counter() - start
print("Python list took:", python_time * 1000, "ms")

Python list took: 103.1768000102602 ms


In [23]:
a1 = np.arange(size)
a2 = np.arange(size)
start = time.perf_counter()
result = a1 + a2
numpy_time = time.perf_counter() - start
print("NumPy took:", numpy_time * 1000, "ms")

NumPy took: 23.382300016237423 ms


### **Q9. Observe Practical Differences (Broadcasting)**

Take the following two structures:

* **Python list:** `[1, 2, 3]`
* **NumPy array:** `np.array([1, 2, 3])`

Multiply both by `2` and observe the difference in outputs.

In [24]:
l = [1,2,3]
l * 2


[1, 2, 3, 1, 2, 3]

In [25]:
a = np.array([1, 2, 3])
a * 2

array([2, 4, 6])

### **Q10. Mini Task ⭐**

Given two lists:

* `prices = [100, 200, 300, 400, 500]`
* `quantity = [2, 3, 1, 4, 2]`

Use NumPy to calculate the total amount for each item ($\text{price} \times \text{quantity}$).

In [26]:
price = np.array([100, 200, 300, 400, 500])
quantity = np.array([2, 3, 1, 4, 2])
price * quantity

array([ 200,  600,  300, 1600, 1000])