🟢 Level 1 — Syntax & Basics

Q1. Create a NumPy array:

[10, 20, 30, 40, 50, 60]

Print:

ndim
shape
size
dtype
itemsize

Q2. Create the following 2D array:

[[10, 20, 30],
 [40, 50, 60]]

Find:

Number of dimensions
Shape
Total number of elements

Q3. Using the array from Q2:

Access 20
Access 50

Use 2D indexing.

Q4. Create a float32 NumPy array:

[10, 20, 30, 40]

Check:

dtype
itemsize
nbytes
🟡 Level 2 — Array Creation

Q5. Create a 3 × 4 array filled with zeros using np.zeros().

Q6. Create a 2 × 5 array filled with ones using np.ones().

Q7. Use np.arange() to create:

[5, 6, 7, 8, 9, 10]

Q8. Use np.arange() to create:

[2, 4, 6, 8, 10, 12]

Q9. Use np.linspace() to generate 5 equally spaced values between 1 and 10.

🟡 Level 3 — Reshaping & Aggregation

Q10. Create:

[1, 2, 3, 4, 5, 6]

Use reshape() to convert it into a 2 × 3 array.

Q11. Convert the same array into a 6 × 1 array using reshape().

Q12. For this array:

a = np.array([[10, 20, 30],
              [40, 50, 60]])

Find:

Minimum
Maximum
Total sum

Q13. For the same array, calculate:

Column-wise sum
Row-wise sum
🟠 Level 4 — Mathematical Operations

Q14. Find the square root of:

[1, 4, 9, 16, 25]

using NumPy.

Q15. Calculate the standard deviation of:

[10, 20, 30, 40, 50]
🟠 Level 5 — Data Analytics Style ⭐

Q16. A store has sales data for 3 products:

sales = np.array([[100, 150, 200],
                  [120, 180, 160],
                  [90,  140, 210]])

Find:

Total sales
Sales of each row
Sales of each column
Maximum sales
Minimum sales

Q17. Employee salaries are:

[25000, 30000, 28000, 35000, 40000]

Using NumPy, find:

Minimum salary
Maximum salary
Average salary
Standard deviation
🔵 Previous Lecture Revision

Q18. Create two NumPy arrays:

[10, 20, 30]
[2, 4, 5]

Perform:

Addition
Subtraction
Multiplication
Division

Q19. Multiply this NumPy array by 2:

[100, 200, 300, 400]

Q20. ⭐ Challenge

price = np.array([100, 200, 300, 400])
quantity = np.array([2, 1, 3, 2])

Find:

Total amount for each product
Overall total revenue
Average product revenue

🟢 Level 1 — Syntax & Basics

Q1. Create a NumPy array:

[10, 20, 30, 40, 50, 60]

Print:

ndim
shape
size
dtype
itemsize

In [1]:
import numpy as np
a = np.array([10, 20, 30, 40, 50, 60])
a.ndim

1

In [2]:
a.shape

(6,)

In [3]:
a.dtype

dtype('int64')

In [ ]:
a.itemsize

8

In [5]:
a.size

6

Q2. Create the following 2D array:

[[10, 20, 30],
 [40, 50, 60]]

Find:

Number of dimensions
Shape
Total number of elements

In [8]:
b = np.array([[10, 20, 30],[40, 50, 60]])
b.ndim

2

In [13]:
b.shape

(2, 3)

In [10]:
b.size

6

Q3. Using the array from Q2:

Access 20
Access 50

Use 2D indexing.

In [14]:
b[0,1]

np.int64(20)

In [15]:
b[1,1]

np.int64(50)

Q4. Create a float32 NumPy array:

[10, 20, 30, 40]

Check:

dtype
itemsize
nbytes

In [16]:
c = np.array([10, 20, 30, 40], dtype=np.float32)
c.dtype

dtype('float32')

In [17]:
c.itemsize

4

In [18]:
c.nbytes

16

🟡 Level 2 — Array Creation

Q5. Create a 3 × 4 array filled with zeros using np.zeros().

In [23]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Q6. Create a 2 × 5 array filled with ones using np.ones().

In [24]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Q7. Use np.arange() to create:

[5, 6, 7, 8, 9, 10]

In [26]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

Q8. Use np.arange() to create:

[2, 4, 6, 8, 10, 12]

In [27]:
np.arange(2,13,2)

array([ 2,  4,  6,  8, 10, 12])

Q9. Use np.linspace() to generate 5 equally spaced values between 1 and 10.

🟡 Level 3 — Reshaping & Aggregation

In [28]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

🟡 Level 3 — Reshaping & Aggregation
Q10. Create:

[1, 2, 3, 4, 5, 6]

Use reshape() to convert it into a 2 × 3 array.

In [29]:
a = np.array([1, 2, 3, 4, 5, 6])
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

Q11. Convert the same array into a 6 × 1 array using reshape().

In [32]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

Q12. For this array:

a = np.array([[10, 20, 30],
              [40, 50, 60]])

Find:

Minimum,
Maximum,
Total sum

In [35]:
a = np.array([[10, 20, 30],
              [40, 50, 60]])
a.min()

np.int64(10)

In [36]:
a.max()

np.int64(60)

In [37]:
a.sum()

np.int64(210)

Q13. For the same array, calculate:

Column-wise sum
Row-wise sum

In [38]:
a.sum(axis=0)

array([50, 70, 90])

In [39]:
a.sum(axis=1)

array([ 60, 150])

🟠 Level 4 — Mathematical Operations

Q14. Find the square root of:

[1, 4, 9, 16, 25]

using NumPy.

In [41]:
a = np.array([1, 4, 9, 16, 25])
np.sqrt(a)

array([1., 2., 3., 4., 5.])

Q15. Calculate the standard deviation of:

[10, 20, 30, 40, 50]

In [42]:
a = np.array([10, 20, 30, 40, 50])
np.std(a)

np.float64(14.142135623730951)

🟠 Level 5 — Data Analytics Style ⭐

Q16. A store has sales data for 3 products:

sales = np.array([[100, 150, 200],
                  [120, 180, 160],
                  [90,  140, 210]])

Find:

Total sales
Sales of each row
Sales of each column
Maximum sales
Minimum sales

In [43]:
sales = np.array([[100, 150, 200],
                  [120, 180, 160],
                  [90,  140, 210]])

In [48]:
sales.sum()

np.int64(1350)

In [49]:
sales.sum(axis=1)

array([450, 460, 440])

In [50]:
sales.sum(axis=0)

array([310, 470, 570])

In [51]:
sales.max()

np.int64(210)

In [52]:
sales.min()

np.int64(90)

Q17. Employee salaries are:

[25000, 30000, 28000, 35000, 40000]

Using NumPy, find:

Minimum salary
Maximum salary
Average salary
Standard deviation

In [53]:
salary = np.array([25000, 30000, 28000, 35000, 40000])
salary.min()

np.int64(25000)

In [54]:
salary.max()

np.int64(40000)

In [55]:
salary.mean()

np.float64(31600.0)

In [56]:
salary.std()

np.float64(5314.132102234569)

Q18. Create two NumPy arrays:

[10, 20, 30]
[2, 4, 5]

Perform:

Addition
Subtraction
Multiplication
Division

In [57]:
a = np.array([10,20,30])
b = np.array([2,4,5])
a + b

array([12, 24, 35])

In [58]:
a - b

array([ 8, 16, 25])

In [59]:
a * b

array([ 20,  80, 150])

In [60]:
a / b

array([5., 5., 6.])

Q19. Multiply this NumPy array by 2:

[100, 200, 300, 400]

In [63]:
arr = np.array([100, 200, 300, 400])
arr*2

array([200, 400, 600, 800])

Q20. ⭐ Challenge

price = np.array([100, 200, 300, 400])
quantity = np.array([2, 1, 3, 2])

Find:

Total amount for each product
Overall total revenue
Average product revenue

In [ ]:
price = np.array([100, 200, 300, 400])
quantity = np.array([2, 1, 3, 2])


In [70]:
product_amounts  = price * quantity
product_amounts

array([200, 200, 900, 800])

In [71]:
total_revenue = price.sum()
total_revenue

np.int64(1000)

In [73]:
avg_revenue = product_amounts.mean()
avg_revenue

np.float64(525.0)