Q1 — Basic Array Creation
Create a NumPy array containing:
[10, 20, 30, 40, 50]
Then print the array.
Write the code yourself without looking at your notes.

In [2]:
import numpy as np
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

Q2 — Element-wise Addition
Create the array:
[10, 20, 30, 40, 50]
Add 5 to every element and print the result.
Don't use a loop.

In [3]:
a = np.array([10, 20, 30, 40, 50])
a + 5

array([15, 25, 35, 45, 55])

Q3 — Element-wise Multiplication
Using the same array:
[10, 20, 30, 40, 50]
Multiply every element by 3 and print the result.

In [6]:
a = np.array([10, 20, 30, 40, 50])
a * 3

array([ 30,  60,  90, 120, 150])

Q4 — Element-wise Subtraction
Using the same array:
[10, 20, 30, 40, 50]
Subtract 5 from every element and print the result.

In [7]:
a = np.array([10, 20, 30, 40, 50])
a - 5

array([ 5, 15, 25, 35, 45])

Q5 — Element-wise Division
Using the same array:
[10, 20, 30, 40, 50]
Divide every element by 5 and print the result.

In [8]:
a = np.array([10, 20, 30, 40, 50])
a / 5

array([ 2.,  4.,  6.,  8., 10.])

Q6 — Combined Arithmetic
Given:
a = np.array([10, 20, 30, 40, 50])


Create a new array where each element is multiplied by 2 and then increased by 5.
Example for the first element:
10 × 2 + 5 = 25
Print the final array.

In [9]:
a = np.array([10, 20, 30, 40, 50])
a * 2 + 5


array([ 25,  45,  65,  85, 105])

Q7 — np.arange()
Create a NumPy array containing numbers from 1 to 10, where 10 is included.
Then print the array.
Think carefully about the stop value in np.arange() before writing the code.

In [ ]:
x = np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Q8 — np.arange() with Step
Create a NumPy array containing:
2, 4, 6, 8, 10, 12
Use np.arange() and print the result.

In [15]:
x = np.arange(2,13,2)
x

array([ 2,  4,  6,  8, 10, 12])

Q9 — arange() with Step
Create the following array using np.arange():
5, 10, 15, 20, 25, 30
Then print it.
Remember: the stop value is excluded.

In [17]:
x = np.arange(5,31,5)
x

array([ 5, 10, 15, 20, 25, 30])

Q10 — NumPy Array vs Python List
Create this Python list:
[10, 20, 30, 40, 50]
Create a NumPy array containing the same values.
Then add 10 to both and observe the difference in their behavior.

In [20]:
l = [10, 20, 30, 40, 50]
l + 10

TypeError: can only concatenate list (not "int") to list

In [21]:
x = np.array([10, 20, 30, 40, 50])
x  + 10

array([20, 30, 40, 50, 60])

Q11 — Memory
Create this NumPy array:
[10, 20, 30, 40, 50]
Then find how many bytes the array elements occupy in memory.

In [35]:
a = np.array([10, 20, 30, 40, 50])
a.nbytes

40

Q12 — np.arange() + Arithmetic
Create an array containing numbers from 1 to 10 using np.arange().
Then multiply every element by 5 and print the result.
Do it in two steps, not one line.

In [36]:
a = np.arange(1,11)
a * 5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

Q13 — Array Arithmetic
Given:
a = np.array([10, 20, 30, 40, 50])b = np.array([2, 4, 5, 8, 10])


Perform element-wise addition and print the result.
Then perform element-wise multiplication and print the result.
No loop.

In [40]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([2, 4, 5, 8, 10])
a + b

array([12, 24, 35, 48, 60])

In [ ]:
a * b

Q14 — Array Creation + Arithmetic
Create a NumPy array containing:
[5, 10, 15, 20, 25]
Then create a new result where:
each element × 2 − 3
Expected result:
[7, 17, 27, 37, 47]
Use NumPy without a loop.

In [41]:
a = np.array([5, 10, 15, 20, 25])
a * 2 - 3

array([ 7, 17, 27, 37, 47])

Q15/15 — Final Lecture 1 Question
A company has 5 products with the following prices:
[100, 200, 300, 400, 500]
The company gives a 10% discount on every product.
Using NumPy:
1. Create the price array.
2. Calculate the discount amount for each product.
3. Calculate the final price after discount.
Hint: 10% = 0.10
Do it without a loop.

In [53]:
price = np.array([100, 200, 300, 400, 500])
discount = price * 0.10
discount

array([10., 20., 30., 40., 50.])

In [51]:
final_price = price - discount
final_price

array([ 90., 180., 270., 360., 450.])