NumPy – Lecture 1
What is NumPy?
Python library for numerical/data operations.
Faster and more memory-efficient than Python lists.
Mainly used for working with arrays.
Import
import numpy as np

In [1]:
import numpy as np
import time
import sys

1. Memory Comparison
l = range(1000)
sys.getsizeof(100) * len(l)
Gives an approximate memory calculation for Python integers.
sys.getsizeof() → size of one Python object in bytes.
len(l) → number of elements.
a = np.arange(1000)
a.nbytes
nbytes → total memory used by NumPy array data.

In [2]:
l = range(1000)
sys.getsizeof(100)*len(l)

28000

In [3]:
a = np.arange(1000)
a.nbytes

8000

2. Speed Comparison
time.perf_counter()
Used to measure execution time accurately.

Python List:

result = [x + y for x, y in zip(l1, l2)]
Adds elements using a Python loop.

NumPy:

result = a1 + a2
Adds elements directly using NumPy's vectorized operation.
time_taken * 1000
Converts seconds → milliseconds.

In [4]:
SIZE = 1000000

l1 = list(range(SIZE))
l2 = list(range(SIZE))
start = time.perf_counter()
result = [x + y for x, y in zip(l1, l2)]
python_time = time.perf_counter() - start
print("Python list took:", python_time * 1000, "ms")

Python list took: 110.6347999884747 ms


In [5]:
a1 = np.arange(SIZE)
a2 = np.arange(SIZE)
start = time.perf_counter()
result = a1 + a2
numpy_time = time.perf_counter() - start
print("NumPy took:", numpy_time * 1000, "ms")

NumPy took: 26.773299992782995 ms


Create Array
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
Basic Operations
a + b
a - b
a * b
a / b

Operations are element-wise.

In [6]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a1+a2

array([5, 7, 9])

In [7]:
a2-a1

array([3, 3, 3])

In [8]:
a1*a2

array([ 4, 10, 18])

In [9]:
a1/a2

array([0.25, 0.4 , 0.5 ])

Key Takeaway

NumPy arrays are designed for numerical operations and are generally faster and more memory-efficient than Python lists.