1. Indexing

Access an element using its index.
a[0]

For 2D arrays:
a[row, column]

In [69]:
import numpy as np
a = np.array([5,6,7])
a[0]

np.int64(5)

2. Array Properties
a.ndim       # Number of dimensions
a.shape      # Rows and columns
a.size       # Total number of elements
a.dtype      # Data type of elements
a.itemsize   # Memory used by each element (bytes)

In [70]:
a = np.array([[1,2],[3,4],[5,6]])
a.ndim

2

In [71]:
a.itemsize

8

In [72]:
a.dtype

dtype('int64')

3. Data Type

Specify the data type while creating an array:
np.array([[1, 2], [3, 4]], dtype=np.float32)
Other example:
dtype=complex

In [73]:
a = np.array([[1,2],[3,4],[5,6]],dtype=np.float32)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)

In [74]:
a.itemsize

4

In [75]:
a.size

6

In [20]:
a.shape

(3, 2)

In [24]:
a = np.array([[1,2],[3,4],[5,6]],dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

4. Creating Arrays
Zeros
np.zeros((3, 4))

Creates an array filled with 0.

In [25]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Ones
np.ones((3, 4))

Creates an array filled with 1.

In [26]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

arange()
np.arange(1, 5)
np.arange(1, 10, 2)

Creates values in a specified range.

In [28]:
np.arange(1,5)

array([1, 2, 3, 4])

In [29]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

linspace()
np.linspace(1, 5, 10)

Creates 10 evenly spaced values between 1 and 5.

In [32]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

5. Reshaping
a.reshape(2, 3)

Changes the shape without changing the data.

a.reshape(6, 1)

The total number of elements must remain the same.

ravel()
a.ravel()

Flattens the array into a 1D array.

In [35]:
a = np.array([[1,2],[3,4],[5,6]])
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [39]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

6. Basic Aggregation
a.min()
a.max()
a.sum()
        min() → minimum value
        max() → maximum value
        sum() → sum of all values

In [54]:
a = np.array([[1,2],[3,4],[5,6]])

In [55]:
a.min()

np.int64(1)

In [42]:
a.max()

np.int64(6)

In [43]:
a.sum()

np.int64(21)

7. Axis
a.sum(axis=0)

Calculates the sum column-wise.

a.sum(axis=1)

Calculates the sum row-wise.

axis=0 → down the rows / column-wise
axis=1 → across the columns / row-wise

In [44]:
a.sum(axis=0)

array([ 9, 12])

In [45]:
a.sum(axis=1)

array([ 3,  7, 11])

8. Mathematical Functions
np.sqrt(a)

Calculates the square root of each element.

np.std(a)

Calculates the standard deviation.

In [56]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [ ]:
np.std(a)

np.float64(1.707825127659933)

9. Array Operations
a + b
a - b
a * b
a / b

Arithmetic operations are performed element-wise.

In [59]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6], [7,8]])
a+b

array([[ 6,  8],
       [10, 12]])

In [60]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [61]:
a*b

array([[ 5, 12],
       [21, 32]])

10. Matrix Multiplication
a.dot(b)

Performs matrix multiplication using the dot product.

In [62]:
a.dot(b)

array([[19, 22],
       [43, 50]])

Key Syntax
a.ndim
a.shape
a.size
a.dtype
a.itemsize
a.nbytes

np.zeros((rows, columns))
np.ones((rows, columns))
np.arange(start, stop, step)
np.linspace(start, stop, number)

a.reshape(rows, columns)
a.ravel()

a.min()
a.max()
a.sum()
a.sum(axis=0)
a.sum(axis=1)

np.sqrt(a)
np.std(a)

a.dot(b)