NumPy — Lecture 3

1. 1D Indexing & Slicing
a[0:2]
   Selects elements from index 0 up to, but not including, index 2.
a[-1]
  -1 selects the last element.

In [1]:
import numpy as np
a = np.array([6,7,8])
a[0:2]

array([6, 7])

In [2]:
a[-1]

np.int64(8)

2. 2D Indexing & Slicing
a[1,0]
    Selects an element using [row, column].
a[0:2,2]
    Selects rows 0–1 from column 2.
a[-1]
    Selects the last row.
a[-1,0:2]
    Selects the last row and columns 0–1.
a[:,1:3]
    : means all rows.
    Selects columns 1–2.

In [3]:
a = np.array([[6,7,8],[1,2,3],[9,3,2]])
a[1,0]

np.int64(1)

In [4]:
a[0:2,2]

array([8, 3])

In [5]:
a[-1]

array([9, 3, 2])

In [6]:
a[-1,0:2]

array([9, 3])

In [7]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

3. Iterating Through Rows
for row in a:
    print(row)
    # Iterates through the array row by row.

In [8]:
a = np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [9]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


4. Iterating Through Elements
for cell in a.flat:
    print(cell)
    # .flat allows iteration through all elements one by one.

In [10]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


5. Stacking Arrays
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
    Creates two 3 × 2 arrays.
np.vstack((a,b))
    Stacks arrays vertically (row-wise).
np.hstack((a,b))
    Stacks arrays horizontally (column-wise).

In [11]:
a=np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)

In [12]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [13]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [14]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [15]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

6. Horizontal Splitting
a = np.arange(30).reshape(2,15)
    Creates a 2 × 15 array.
np.hsplit(a,3)
    Splits the array horizontally into 3 parts.
result[0]
result[1]
result[2]
Accesses each split part.

In [16]:
a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [17]:
result = np.hsplit(a,3)
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [18]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [19]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [20]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

7. Vertical Splitting
np.vsplit(a,2)
   Splits the array vertically into 2 parts.
result[0]
result[1]
Accesses each split part.

In [21]:
result = np.vsplit(a,2)
result

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [22]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [23]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

8. Boolean Indexing
a = np.arange(12).reshape(3,4)
    Creates a 3 × 4 array.
b = a > 4
    Creates a Boolean array.
    Each element becomes True if it is greater than 4, otherwise False.
a[b]
    Selects only elements where the condition is True.
a[b] = -1
    Replaces all elements satisfying the condition with -1.

In [24]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [26]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [27]:
a[b]=-1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

Key Syntax
a[start:stop]
a[row, column]
a[:, start:stop]

for row in a:
for cell in a.flat:

np.vstack((a,b))
np.hstack((a,b))

np.hsplit(a, parts)
np.vsplit(a, parts)

a > value
a[condition]
a[condition] = value