In [14]:
import numpy as np

In [15]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

1. Iterating Through Rows
A for loop can iterate through a 2D array row by row.
Each iteration gives one complete row.

In [16]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


2. Nested Loop
An outer loop can iterate through rows.
An inner loop can iterate through each individual element.

In [17]:
for row in a:
    for cell in row:
     print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


3. flatten()
flatten() converts a multi-dimensional array into a 1D array.
Useful when you want to iterate through all elements one by one.

In [18]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


4. np.nditer()
np.nditer() is used to iterate through NumPy arrays efficiently.
It provides more control over how the array is traversed.

5. C Order
order='C' → elements are traversed row by row.
This is the normal C-style order.

In [24]:
for x in np.nditer(a,order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


6. F Order
order='F' → elements are traversed column by column.
F means Fortran-style order.

In [28]:
for x in np.nditer(a, order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


7. external_loop
external_loop makes nditer() return elements in groups/chunks instead of one at a time.

In [30]:
for x in np.nditer(a,order='F',flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


8. op_flags=['readwrite']
readwrite allows the elements of the original array to be modified during iteration.
Without readwrite, elements are normally read-only.

In [31]:
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=x*x

In [32]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [33]:
b = np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

9. Iterating Two Arrays
np.nditer() can iterate through two arrays at the same time.
If their shapes are compatible, NumPy uses broadcasting.

In [34]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11


Key Points
for → simple iteration
flatten() → converts to 1D
nditer() → controlled iteration
C order → row-wise
F order → column-wise
external_loop → groups of elements
readwrite → allows modification
Multiple arrays → can use broadcasting